import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  girl1,
  girl2,
  girl3,
  boy1,
  gbluedenim,
  gbwpant,
  ggreencoat,
  gwhiteshirt,
  bblackovershirt,
  bblackfloralshirt,
  bbrownjacket,
  gwhiteshirt2,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
} from "../images/index";
// =================== NavBarList End here ======================
// =================== Special Offer data Start here ============
export const SplOfferData = [
  {
    _id: 201,
    img: girl1,
    productName: "Short Skert ",
    stock: 9,
    price: "35.00",
    color: "Blue",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 202,
    img: girl2,
    productName: "Red Coat",
    stock: 7,
    price: "180.00",
    color: "Red",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 203,
    img: boy1,
    productName: "Over Coat",
    stock: 10,
    price: "25.00",
    color: "Yellow",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 204,
    img: girl3,
    productName: "Sweat Shirt",
    stock: 4,
    price: "220.00",
    color: "Grey",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
// =================== Special Offer data End here ==============

// =================== PaginationItems Start here ===============

export const paginationItems = [
  {
    _id: 1001,
    img: girl1,
    productName: "Short Skert ",
    stock: 9,
    price: "35.00",
    color: "Blue",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: girl2,
    productName: "Red Coat",
    stock: 7,
    price: "180.00",
    color: "Red",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: boy1,
    productName: "Over Coat",
    stock: 10,
    price: "25.00",
    color: "Yellow",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1004,
    img: girl3,
    productName: "Sweat Shirt",
    stock: 4,
    price: "220.00",
    color: "Grey",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },


  {
    _id: 1009,
    img: gbluedenim,
    productName: "Denim Shirt",
    price: "44.00",
    color: "Denim blue",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1010,
    img: gbwpant,
    productName: "Pant",
    price: "250.00",
    color: "Black and White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: ggreencoat,
    productName: "Jacket",
    price: "80.00",
    color: "Green",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1012,
    img: gwhiteshirt,
    productName: "White Shirt",
    price: "60.00",
    color: "White",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1017,
    img: bblackovershirt,
    productName: "Over Shirt",
    price: "220.00",
    color: "Black",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1018,
    img: bbrownjacket,
    productName: "Jacket",
    price: "44.00",
    color: "Brown",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1019,
    img: bblackfloralshirt,
    productName: "Floral shirt",
    price: "250.00",
    color: "Black and Mixed",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1020,
    img: gwhiteshirt2,
    productName: "Shirt",
    price: "80.00",
    color: "White",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  }
];
// =================== PaginationItems End here =================
